// Search engines that ship pre-described.
//
// ── Why these are data and not code ────────────────────────────────────────────────────────────
//
// Seven engines have hand-written adapters because their shapes needed code — Exa reports its own
// cost, OpenRouter is not a SERP API at all. The rest do not. A SERP API is a query in a request and
// a ranked list somewhere in the JSON, and that is exactly what `CustomSearchSpec` describes.
//
// Writing twenty adapters would mean twenty request shapes I cannot all verify, each failing
// silently and identically: a wrong path returns zero results on every row and looks like a question
// nobody could answer. As DATA the same mistake is a two-minute fix in a form rather than a release,
// and the Try button proves each one before it ever runs on a column.
//
// So treat every entry below as a STARTING POINT, not a guarantee. Vendors move endpoints and rename
// fields; this file will be out of date somewhere the day it is written. That is survivable here and
// would not be if these were compiled in.
//
// ── Prices ──────────────────────────────────────────────────────────────────────────────────────
//
// Mostly absent, deliberately. Nearly all of these bill from a credit balance or a monthly plan
// rather than per search, and a per-call figure invented for them would be enforced by the per-cell
// budget as if it were real. Where a headline rate is well known it is filled in as a default the
// user can correct; where it is not, the field is left empty and the screen asks.

import type { CustomSearchSpec } from "./custom.ts";

export interface SearchPreset extends Omit<CustomSearchSpec, "id"> {
  /** Slug used to build the id when it is added. */
  key: string;
  /** Where to get a key. */
  signupUrl: string;
  /** Named so the key field can prompt for exactly this secret. */
  secretNames: string[];
  /** One line on what it is good at, since twenty names alone is not a choice. */
  note: string;
}

const P = (p: SearchPreset): SearchPreset => p;

export const SEARCH_PRESETS: SearchPreset[] = [
  P({
    key: "dataforseo",
    label: "DataForSEO",
    signupUrl: "https://app.dataforseo.com/api-access",
    secretNames: ["DataForSEO"],
    note: "Google SERPs at wholesale rates, with location and language targeting. Cheapest at volume.",
    method: "POST",
    url: "https://api.dataforseo.com/v3/serp/google/organic/live/advanced",
    // Basic auth: store `login:password` base64-encoded as the secret. It goes in a header, so the
    // `+` and `/` base64 produces are safe.
    headers: [{ name: "Authorization", value: "Basic {{secret:DataForSEO}}" }],
    // A raw body because DataForSEO takes an ARRAY of tasks, which named fields cannot express.
    // `{{query}}` is JSON-escaped in a raw body, so a quote in the query cannot break out.
    bodyMode: "raw",
    bodyFields: [],
    body: '[{"keyword":"{{query}}","language_code":"en","location_code":2840,"depth":{{maxResults}}}]',
    resultsPath: "tasks.0.result.0.items",
    urlField: "url",
    titleField: "title",
    snippetField: "description",
    costPath: "cost",
  }),
  P({
    key: "serpapi",
    label: "SerpApi",
    signupUrl: "https://serpapi.com/manage-api-key",
    secretNames: ["SerpApi"],
    note: "The long-standing one. Many engines behind a single shape, generous free tier to try.",
    method: "GET",
    url: "https://serpapi.com/search.json?engine=google&q={{query}}&num={{maxResults}}&api_key={{secret:SerpApi}}",
    headers: [],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "organic_results",
    urlField: "link",
    titleField: "title",
    snippetField: "snippet",
    costPath: "",
  }),
  P({
    key: "searchapi",
    label: "SearchApi.io",
    signupUrl: "https://www.searchapi.io/",
    secretNames: ["SearchApi"],
    note: "Google, Bing, YouTube and more behind one endpoint.",
    method: "GET",
    url: "https://www.searchapi.io/api/v1/search?engine=google&q={{query}}&num={{maxResults}}",
    headers: [{ name: "Authorization", value: "Bearer {{secret:SearchApi}}" }],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "organic_results",
    urlField: "link",
    titleField: "title",
    snippetField: "snippet",
    costPath: "",
  }),
  P({
    key: "valueserp",
    label: "ValueSERP",
    signupUrl: "https://app.valueserp.com/",
    secretNames: ["ValueSerp"],
    note: "Google results, priced low per search.",
    method: "GET",
    url: "https://api.valueserp.com/search?api_key={{secret:ValueSerp}}&q={{query}}&num={{maxResults}}",
    headers: [],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "organic_results",
    urlField: "link",
    titleField: "title",
    snippetField: "snippet",
    costPath: "",
  }),
  P({
    key: "scaleserp",
    label: "ScaleSERP",
    signupUrl: "https://app.scaleserp.com/",
    secretNames: ["ScaleSerp"],
    note: "Same family as ValueSERP, aimed at higher volume.",
    method: "GET",
    url: "https://api.scaleserp.com/search?api_key={{secret:ScaleSerp}}&q={{query}}&num={{maxResults}}",
    headers: [],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "organic_results",
    urlField: "link",
    titleField: "title",
    snippetField: "snippet",
    costPath: "",
  }),
  P({
    key: "google-cse",
    label: "Google Programmable Search",
    signupUrl: "https://programmablesearchengine.google.com/",
    secretNames: ["GoogleCSE", "GoogleCSECx"],
    note: "Google's own API. Needs two values: an API key and a search-engine id (cx). Free up to 100 a day.",
    method: "GET",
    url: "https://www.googleapis.com/customsearch/v1?key={{secret:GoogleCSE}}&cx={{secret:GoogleCSECx}}&q={{query}}&num={{maxResults}}",
    headers: [],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "items",
    urlField: "link",
    titleField: "title",
    snippetField: "snippet",
    costPath: "",
  }),
  P({
    key: "bing",
    label: "Bing Search (Azure)",
    signupUrl: "https://portal.azure.com/",
    secretNames: ["Bing"],
    note: "Microsoft's index through Azure. Check availability — Microsoft has been retiring this API.",
    method: "GET",
    url: "https://api.bing.microsoft.com/v7.0/search?q={{query}}&count={{maxResults}}",
    headers: [{ name: "Ocp-Apim-Subscription-Key", value: "{{secret:Bing}}" }],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "webPages.value",
    urlField: "url",
    titleField: "name",
    snippetField: "snippet",
    costPath: "",
  }),
  P({
    key: "kagi",
    label: "Kagi",
    signupUrl: "https://kagi.com/settings?p=api",
    secretNames: ["Kagi"],
    note: "Independent index, no ads, strong on technical queries. Invite-gated API.",
    method: "GET",
    url: "https://kagi.com/api/v0/search?q={{query}}&limit={{maxResults}}",
    headers: [{ name: "Authorization", value: "Bot {{secret:Kagi}}" }],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "data",
    urlField: "url",
    titleField: "title",
    snippetField: "snippet",
    costPath: "",
  }),
  P({
    key: "you",
    label: "You.com",
    signupUrl: "https://api.you.com/",
    secretNames: ["YouCom"],
    note: "Built for feeding models — returns extracted passages rather than link blurbs.",
    method: "GET",
    url: "https://api.ydc-index.io/search?query={{query}}",
    headers: [{ name: "X-API-Key", value: "{{secret:YouCom}}" }],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "hits",
    urlField: "url",
    titleField: "title",
    snippetField: "description",
    costPath: "",
  }),
  P({
    key: "linkup",
    label: "Linkup",
    signupUrl: "https://app.linkup.so/",
    secretNames: ["Linkup"],
    note: "Answers with sourced passages, aimed at research agents.",
    method: "POST",
    url: "https://api.linkup.so/v1/search",
    headers: [{ name: "Authorization", value: "Bearer {{secret:Linkup}}" }],
    bodyMode: "json",
    bodyFields: [
      { name: "q", value: "{{query}}" },
      { name: "depth", value: "standard" },
      { name: "outputType", value: "searchResults" },
    ],
    body: "",
    resultsPath: "results",
    urlField: "url",
    titleField: "name",
    snippetField: "content",
    costPath: "",
  }),
  P({
    key: "searxng",
    label: "SearXNG (self-hosted)",
    signupUrl: "https://docs.searxng.org/",
    secretNames: ["SearxngUrl"],
    note: "Run it yourself and searching is FREE — no per-call charge at all. Store your instance's base address as the secret.",
    method: "GET",
    url: "{{secret:SearxngUrl}}/search?q={{query}}&format=json",
    headers: [],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "results",
    urlField: "url",
    titleField: "title",
    snippetField: "content",
    costPath: "",
    cost: { unit: "searches", perCall: 1, packUnits: 1, packUsd: 0 },
  }),
  P({
    key: "mojeek",
    label: "Mojeek",
    signupUrl: "https://www.mojeek.com/services/search/web-search-api/",
    secretNames: ["Mojeek"],
    note: "An independent crawler and index — genuinely different results from anything Google-derived.",
    method: "GET",
    url: "https://www.mojeek.com/search?q={{query}}&fmt=json&t={{maxResults}}",
    headers: [{ name: "Authorization", value: "Bearer {{secret:Mojeek}}" }],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "response.results",
    urlField: "url",
    titleField: "title",
    snippetField: "desc",
    costPath: "",
  }),
  P({
    key: "scrapingbee",
    label: "ScrapingBee (Google)",
    signupUrl: "https://app.scrapingbee.com/account/register",
    secretNames: ["ScrapingBee"],
    note: "Its Google endpoint. Useful if you already use it for scraping and want one bill.",
    method: "GET",
    url: "https://app.scrapingbee.com/api/v1/store/google?api_key={{secret:ScrapingBee}}&search={{query}}&nb_results={{maxResults}}",
    headers: [],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "organic_results",
    urlField: "url",
    titleField: "title",
    snippetField: "description",
    costPath: "",
  }),
  P({
    key: "zenrows",
    label: "ZenRows SERP",
    signupUrl: "https://app.zenrows.com/register",
    secretNames: ["ZenRows"],
    note: "SERP endpoint from a scraping provider — again, one account for both jobs.",
    method: "GET",
    url: "https://serp.api.zenrows.com/v1/targets/google/search/{{query}}?apikey={{secret:ZenRows}}",
    headers: [],
    bodyMode: "none",
    bodyFields: [],
    body: "",
    resultsPath: "organic",
    urlField: "url",
    titleField: "title",
    snippetField: "description",
    costPath: "",
  }),
  P({
    key: "oxylabs",
    label: "Oxylabs",
    signupUrl: "https://oxylabs.io/",
    secretNames: ["Oxylabs"],
    note: "Enterprise scale and enterprise pricing. Store `user:pass` base64-encoded.",
    method: "POST",
    url: "https://realtime.oxylabs.io/v1/queries",
    headers: [{ name: "Authorization", value: "Basic {{secret:Oxylabs}}" }],
    bodyMode: "json",
    bodyFields: [
      { name: "source", value: "google_search" },
      { name: "query", value: "{{query}}" },
      { name: "parse", value: "true" },
    ],
    body: "",
    resultsPath: "results.0.content.results.organic",
    urlField: "url",
    titleField: "title",
    snippetField: "desc",
    costPath: "",
  }),
  P({
    key: "brightdata",
    label: "Bright Data SERP",
    signupUrl: "https://brightdata.com/",
    secretNames: ["BrightData", "BrightDataZone"],
    note: "Needs a zone as well as a token. Large-scale and heavily configurable.",
    method: "POST",
    url: "https://api.brightdata.com/request",
    headers: [{ name: "Authorization", value: "Bearer {{secret:BrightData}}" }],
    bodyMode: "json",
    bodyFields: [
      { name: "zone", value: "{{secret:BrightDataZone}}" },
      { name: "url", value: "https://www.google.com/search?q={{query}}&brd_json=1" },
      { name: "format", value: "raw" },
    ],
    body: "",
    resultsPath: "organic",
    urlField: "link",
    titleField: "title",
    snippetField: "description",
    costPath: "",
  }),
];

export function preset(key: string): SearchPreset | null {
  return SEARCH_PRESETS.find((p) => p.key === key) ?? null;
}
